cmd/root: don't double print errors
If not explicitly disabled, cobra prints errors in `cmd.Execute`, i.e.
no need to log it a second time.

https://github.com/spf13/cobra/blob/fe5e611709b0c57fa4a89136deaa8e1d4004d053/command.go#L863-L865

Currently the user gets to see:

```
Error: Kubeconfig "/home/schu/.kube/config" not found
[...]
FATA[0000] Error in executing lokoctl: Kubeconfig "/home/schu/.kube/config" not found
```