aws: add support for flatcar-edge
aws_ami.coreos and aws_ami.flatcar are always evaluated because they are
dependencies for ami_id, even if only one of them will be used at the
end.

That worked fine as long as coreos and flatcar have the same channels.
But when starting to use flatcar-edge, I was getting the following
error:

```
data.aws_ami.flatcar: Refreshing state...
data.aws_ami.coreos: Refreshing state...

Error: Error refreshing state: 2 error(s) occurred:

* module.aws-edgedemo.module.workers.data.aws_ami.coreos: 1 error(s) occurred:

* module.aws-edgedemo.module.workers.data.aws_ami.coreos: data.aws_ami.coreos: Your query returned no results. Please change your search criteria and try again.
* module.aws-edgedemo.data.aws_ami.coreos: 1 error(s) occurred:

* module.aws-edgedemo.data.aws_ami.coreos: data.aws_ami.coreos: Your query returned no results. Please change your search criteria and try again.

FATA[0003] error installing cluster on AWS: exit status 1  args="[]" command="lokoctl cluster install"
```

As a workaround, this patch forces aws_ami.coreos to be evaluated on the
stable channel when using flatcar (and similar for aws_ami.flatcar).