aws_ebs_csi_driver: fix permission issue
Fixes: #1219

Whe trying to dynamically provision EBS volumes using the AWS EBS CSI
driver, we run into an error:
```
E1217 08:08:41.495598       1 driver.go:111] GRPC error: rpc error: code
= Internal desc = NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the
environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
```

There reason being that worker nodes are not given this permissions as
mentioned in the github repo of
[aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver#set-up-driver-permission).

This commit adds such permissions to the worker nodes.

Signed-off-by: Imran Pochi <imran@kinvolk.io>